name: Publish npm dev

on:
  push:
    branches: [ main ]

jobs:
  test:
    uses: ./.github/workflows/unit-test.yml

  publish-npm-dev:
    needs: test

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: Publish package on npm
        run: ./scripts/publish-dev.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
